export const SAVE_FILE_REQUEST = "SAVE_FILE_REQUEST";
export const SAVE_FILE_SUCCESS = "SAVE_FILE_SUCCESS";
export const SAVE_FILE_FAILURE = "SAVE_FILE_FAILURE";

export const OPEN_FILE_REQUEST = "OPEN_FILE_REQUEST";
export const OPEN_FILE_SUCCESS = "OPEN_FILE_SUCCESS";
export const OPEN_FILE_FAILURE = "OPEN_FILE_FAILURE";

export const INSERT_MEDIA_REQUEST = "INSERT_MEDIA_REQUEST";
export const INSERT_MEDIA_SUCCESS = "INSERT_MEDIA_SUCCESS";
export const INSERT_MEDIA_FAILURE = "INSERT_MEDIA_FAILURE";

export const CHANGE_PATH = "CHANGE_PATH";
export const ADD_URL = "ADD_URL";
export const NEW_FILE = "NEW_FILE";